fix wf-17

diff --git a/.github/workflows/validate.js.yml b/.github/workflows/validate.js.yml
--- a/.github/workflows/validate.js.yml
+++ b/.github/workflows/validate.js.yml
@@ -16,48 +16,56 @@ jobs:
             - name: Checkout
               uses: actions/checkout@v2
 
-            # - name: Install Packer
-            #   run: |
-            #     cd packer
-            #     chmod +x install.sh
-            #     wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
-            #     sudo rm -f /usr/local/bin/packer
-            #     unzip -o packer_1.7.4_linux_amd64.zip
-            #     sudo mv packer /usr/local/bin/
-            #     packer --version
-            #     sudo rm packer_1.7.4_linux_amd64.zip
-
-            # - name: Packer Init
-            #   run: |
-            #     packer init packer/aws-debian.pkr.hcl
-
-            # - name: Format Packer Template
-            #   run: |
-            #     packer fmt packer/aws-debian.pkr.hcl
-
-            # - name: Validate Packer Template
-            #   run: |
-            #     cd packer
-            #     packer validate aws-debian.pkr.hcl
-
-            - name: Set permission
+            - name: Install Packer
               run: |
+                cd packer
                 chmod +x install.sh
+                wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
+                sudo rm -f /usr/local/bin/packer
+                unzip -o packer_1.7.4_linux_amd64.zip
+                sudo mv packer /usr/local/bin/
+                packer --version
+                sudo rm packer_1.7.4_linux_amd64.zip
 
             - name: Packer Init
-              uses: hashicorp/packer-github-actions@master
-              with:
-                command: init
-                target: aws-debian.pkr.hcl
+              run: |
+                packer init packer/aws-debian.pkr.hcl
 
             - name: Format Packer Template
-              uses: hashicorp/packer-github-actions@master
-              with:
-                command: fmt
-                target: aws-debian.pkr.hcl
+              run: |
+                packer fmt packer/aws-debian.pkr.hcl
+                if [ $? -ne 0]; then
+                    echo "Packer template format is incorrect."
+                    exit 1
+                fi
 
-            - name: Validate Packer 
-              uses: hashicorp/packer-github-actions@master
-              with:
-                command: validate
-                target: aws-debian.pkr.hcl
+            - name: Validate Packer Template
+              run: |
+                cd packer
+                packer validate aws-debian.pkr.hcl
+                if [ $? -ne 0 ]; then
+                    echo "Packer template validation failed."
+                    exit 1
+                fi
+
+            # - name: Set permission
+            #   run: |
+            #     chmod +x install.sh
+
+            # - name: Packer Init
+            #   uses: hashicorp/packer-github-actions@master
+            #   with:
+            #     command: init
+            #     target: aws-debian.pkr.hcl
+
+            # - name: Format Packer Template
+            #   uses: hashicorp/packer-github-actions@master
+            #   with:
+            #     command: fmt
+            #     target: aws-debian.pkr.hcl
+
+            # - name: Validate Packer 
+            #   uses: hashicorp/packer-github-actions@master
+            #   with:
+            #     command: validate
+            #     target: aws-debian.pkr.hcl
